[package]
name = "testing-library-dom"
description = "Rust port of DOM Testing Library."
homepage = "https://testing-library.rustforweb.org"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
aria-query = "0.0.3"
dom-accessibility-api = "0.0.2"
log.workspace = true
paste = "1.0.15"
pretty-format = { path = "../pretty-format", version = "0.0.1" }
regex.workspace = true
thiserror.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
    "Attr",
    "Comment",
    "Document",
    "DocumentFragment",
    "Element",
    "HtmlCollection",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlLabelElement",
    "HtmlOptionElement",
    "HtmlOptionsCollection",
    "HtmlSelectElement",
    "NamedNodeMap",
    "NodeList",
    "Text",
    "Window",
] }

[dev-dependencies]
indoc = "2.0.5"
mockall = "0.13.0"
wasm-bindgen-test.workspace = true
