[package]
name = "testing-library-dom"
description = "Rust port of DOM Testing Library."
homepage = "https://testing-library.rustforweb.org"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
log.workspace = true
paste = "1.0.15"
regex.workspace = true
thiserror.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
    "Document",
    "Element",
    "HtmlCollection",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlOptionElement",
    "HtmlOptionsCollection",
    "HtmlSelectElement",
    "NodeList",
    "Window",
] }

[dev-dependencies]
wasm-bindgen-test.workspace = true
mockall = "0.13.0"
